#!/bin/sh


### BEGIN INIT INFO
# Provides:       easy
# Required-Start: $network $remote_fs
# Required-Stop:  
# Default-Start:  2 3 5
# Default-Stop:
# Description:    Start the EasyInetAccess service server
### END INIT INFO


EASY_PATH=/usr/easy
LOGFILE=/var/log/easy.log


case "$1" in

    start)
        echo -n "Starting EasyInetAccess services"
        echo -n "-- Started: " >> ${LOGFILE}
        date >> ${LOGFILE}
        #${EASY_PATH}/bin/iproute start
        ${EASY_PATH}/bin/aaa.py
        cd ${EASY_PATH}/web && ./http_serv.py
  
        rc_status -v
        ;;

    stop)
        echo -n "Shutting down EasyInetAccess services"
        echo -n "-- Stoped: " >> ${LOGFILE}
        date >> ${LOGFILE}
        #${EASY_PATH}/bin/iproute stop
        killall http_serv.py

        rc_status -v
        ;;

    restart)
        echo "Restarting service EasyInetAccess "
        $0 stop
        $0 start
        
        rc_status
        ;;  
    
esac
rc_exit


