#!/bin/bash

INSTDIR=/usr/local/easy
LOGFILE=/var/log/easy.log

#TODO 
# 1. Create user + 
# 2. Create DB
# 3. Update Cron  

# Create user easy
adduser --no-create-home --disabled-login easy

#Create, prepare and copy to install dir
if [ -e ${INSTDIR} ]; then 
echo ;
else
mkdir ${INSTDIR};
fi

cp -R * ${INSTDIR}/
rm ${INSTDIR}/install
chown -R easy:easy ${INSTDIR}/
chmod 0755 ${INSTDIR}
chmod -R 0500 ${INSTDIR}/*
chmod 0700 ${INSTDIR}/bin
chmod 0700 ${INSTDIR}/cfg
chmod 0700 ${INSTDIR}/web
chmod 0700 ${INSTDIR}/web/cgi-bin


#Create LOG file
if [ -e ${INSTDIR} ]; then 
echo --Install-- >> ${LOGFILE}
else
echo --Install-- > ${LOGFILE}
fi

chown easy:easy ${LOGFILE}
chmod 0600 ${LOGFILE}


#Create service
cp ${INSTDIR}/bin/easy /etc/init.d
updare-rc.d easy defaults
#insserv -r easybs
#insserv easybs
