#!/bin/bash

INSTDIR=/usr/local/easy
LOGFILE=/var/log/easy.log

# Create user easy
adduser --no-create-home --disabled-login easy

# Crontab entry
#TODO!

# Cehck instalation dir
if [ -e ${INSTDIR} ]; then 
    echo;
else
    # Create instalation dir
    mkdir ${INSTDIR}
    # Create DB
    cd ${INSTDIR}/db && python init_db.py
fi

# Copy files, set up permissions
cp -R ./bin ${INSTDIR}/
cp -R ./cfg ${INSTDIR}/
cp -R ./web ${INSTDIR}/
chown -R easy:easy ${INSTDIR}/
chmod 0755 ${INSTDIR}
chmod -R 0500 ${INSTDIR}/*
chmod 0700 ${INSTDIR}/bin
chmod 0700 ${INSTDIR}/cfg
chmod 0700 ${INSTDIR}/db
chmod 0700 ${INSTDIR}/db/easy.db
chmod 0700 ${INSTDIR}/web
chmod 0700 ${INSTDIR}/web/cgi-bin


# Create LOG file
if [ -e ${INSTDIR} ]; then 
echo --Install-- >> ${LOGFILE}
else
echo --Install-- > ${LOGFILE}
fi
chown easy:easy ${LOGFILE}
chmod 0644 ${LOGFILE}


# Install service
cp ./easy /etc/init.d
# Debian
update-rc.d easy defaults
update-rc.d easy enable
# SuSE
#insserv -r easy
#insserv easy
